//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieCatalog.Models
{
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Movie
    /// </summary>
    public partial class Movie
    {
        /// <summary>
        /// Movie id
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Movie name
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// Movie description
        /// </summary>
        [Required]
        public string Description { get; set; }

        /// <summary>
        /// Movie released date
        /// </summary>
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:yyyy-MM-dd}", ApplyFormatInEditMode =true)]
        public System.DateTime DateReleased { get; set; }

        /// <summary>
        /// Movie director
        /// </summary>
        [Required]
        public string Director { get; set; }

        /// <summary>
        /// User, who posted movie
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// Movie poster
        /// </summary>
        public byte[] Poster { get; set; }
    }
}
